image: mcr.microsoft.com/playwright:v1.43.1-jammy

stages:
  - main

variables:
  NODE_ENV: "mian"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

before_script:
  - npm i --save-dev --no-audit
  - npm ci
  - npx playwright install --with-deps

playwright_tests:
  stage: main
  script:
    - HEADLESS=true npx playwright test test-suite/smoke/login.test.ts
  artifacts:
    when: always
    paths:
      - reports/
    expire_in: 1 week
