- pipeline: null-
  actions:
  - action: npm test
    type: BUILD
    docker_image_name: library/node
    docker_image_tag: 22
    execute_commands:
    - "# yarn install"
    - npm install
    - npm test
    shell: BASH
