- pipeline: "Build"
  on: "EVENT"
  events:
  - type: "PUSH"
  resources: "DEFAULT"
  actions:
  - action: "build"
    type: "BUILD"
    docker_image_name: "library/node"
    docker_image_tag: "20"
    execute_commands:
      - npm ci
      - npm install --save-dev --no-audit
      - npx playwright install --with-deps
      - HEADLESS=true npx playwright test
  - action: "Email"
    type: "EMAIL"
    title: "Playwright Test"
    from_name: "Buddy"
    content: "<b>${BUDDY_PIPELINE_NAME}</b> execution #${BUDDY_RUN_ID}"
    recipients:
      - "santhosh.g@calibraint.com"
      - "krishnakumar@calibraint.com"
      - "santhoshjeeva440@gamil.com"
    send_as_html: true
    variables:
    - key: "title"
      value: "Pipeline executed successfully!"
    file_attachments:
    - $BUDDY_EXECUTION_ARTIFACTS_URL}