- pipeline: "Build"
  on: "EVENT"
  events:
  - type: "PUSH"
  resources: "DEFAULT"
  actions:
  - action: "build"
    type: "BUILD"
    docker_image_name: "library/node"
    docker_image_tag: "20"
    execute_commands:
      - npm ci
      - npm install --save-dev --no-audit
      - npx playwright install --with-deps
      - HEADLESS=true npx playwright test

  - action: "Filesystem"
    name: "Upload Playwright Artifacts"
    direction: "upload"
    source_path: 
      - "playwright-report/"
      - "test-results/"
    artifact_name: "playwright-artifacts"

  - action: "Email"
    name: "Notify QA Team"
    to: 
      - "santhosh.g@calibraint.com"
      - "santhoshjeeva440@gmail.com"
    subject: "✅ Playwright Tests Completed on $BUDDY_PROJECT_NAME"
    body: |
      Hello team,

      The Playwright tests have completed in Buddy for project **$BUDDY_PROJECT_NAME**.

      ✅ Status: **$BUDDY_EXECUTION_STATUS**
      🕒 Started at: $BUDDY_EXECUTION_START_DATE
      🔗 View the test artifacts and report: $BUDDY_EXECUTION_ARTIFACTS_URL

      Cheers,
      Your CI Pipeline 🤖
